### ISSUE TITLE
.dll not working

### ISSUE THREAD

**Issue by camrun91** [ApollosProject/apollos-onesignal#4]
I copied over the .dll and .pdb file from the bin folder. These both caused errors when I went to the communication transport in Rock. However the cc.Newspring .dll and .pdb in obj/debug worked fine. I do not know what the difference is in the two but thought I would make it known.

**Comment by conrad-vanl** [comment]
@camrun91 thanks for submitting this! Looks like we don't have an issue template set up for this repo, but some information that would be helpful to help us understand:

- What version of Rock?
- Steps of what you did to produce this issue
- Error logs or any other information you might be able to get from Rock about the specific errors thrown

**Comment by camrun91** [comment]
Rock version Rock McKinley 9.4 (1.9.4.1)
I followed the guide on https://apollosapp.io/docs/one-signal (I know these are not complete yet)

The errors from Rock are as follows:
Unable to load MEF from apollosProject.OneSignal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
and
Method 'Send' in type 'Rock.Communication.Transport.OneSignal' from assembly 'apollosProject.OneSignal, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by conrad-vanl** [comment]
@richarddubay can speak better into this, but I don't know that this transport supports rock 9. Maybe only 10 and above? I don't recall 100%

**Comment by camrun91** [comment]
Just as a side note. The .dll that is labeled as newspring in the obj/debug folder worked when I copied it over instead of the one in the bin folder.

**Comment by conrad-vanl** [comment]
Interesting. I bet that one is the older version of the transport. Interesting that it made it into this repo in the first place, if so. You might be able to use that one without issue, but I'm not sure what it is missing. We'll have to wait for Rich to chime in

**Comment by richarddubay** [comment]
Hey @camrun91!

The difference between the 2 sets of DLLs is that I made a change back in November to remove some "Obsolete" functions (like the `Send` your error is showing). The `cc.NewSpring` DLLs in that `obj` folder work because they weren't recompiled with the new code. They should probably be removed for clarity. 

I don't remember off the top of my head which version of Rock this needs now, but yeah, I can safely say that version 9 isn't it.

**Comment by conrad-vanl** [comment]
Willowcreek is using this transport and they're on Rock McKinley 10.1 (1.10.1.4)

**Comment by camrun91** [comment]
ah ok we do not have access to v10 yet as we are in the process of setting rock up still. Hoping to go live in September.

**Comment by richarddubay** [comment]
You could continue to use those NewSpring DLLs if you want, but I'd treat them like a `beta` at this point. They could or could not work at any point as you upgrade things.

**Comment by camrun91** [comment]
OK I will go that route. Thanks!
